export enum ORDER_TOPIC {
    CREATE_ORDER_COMPLETED = 'CREATE_ORDER_COMPLETED',
    CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
}

export enum TOPIC {
    ORCHESTRATOR = 'ORCHESTRATOR-SERVICE-2',
    ORDER = 'ORDER-SERVICE-3',
}