export enum SHIPPING_TOPIC {
    SHIPPING_COMPLETED = 'SHIPPING_COMPLETED',
    SHIPPING_FAIL = 'SHIPPING_FAIL',
}

export enum TOPIC {
    ORCHESTRATOR = 'ORCHESTRATOR-SERVICE-2',
    SHIPPING = 'SHIPPING-SERVICE',
}