export enum PAYMENT_TOPIC {
    PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
    PAYMENT_FAIL = 'PAYMENT_FAIL',
}

export enum TOPIC {
    ORCHESTRATOR = 'ORCHESTRATOR-SERVICE-2',
    PAYMENT = 'PAYMENT-SERVICE',
}